### ISSUE TITLE
RegexMatchError when "Getting pytube url"

### ISSUE THREAD

**Issue by DavidBerdik** [wes1993/YouTubeForAlexa#15]
I am having an issue with the skill failing at the "Getting pytube url" stage with a RegexMatchError. For example, when I try to use the example "play videos by The Beatles" phrase, Alexa "thinks" for 20 seconds or so and then gives up. When I check the CloudWatch logs resulting from the interaction, I see the following entry, which I suspect is the problem:

```
[INFO]	2022-06-04T02:25:44.705Z	0dbc7c67-1523-4d4b-b2fb-1a54a8fe5907	Getting pytube url for https://www.youtube.com/watch?v=RS7trxkb0zE
[ERROR] RegexMatchError: __init__: could not find match for ^\w+\W
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 248, in lambda_handler
    return on_intent(event)
  File "/var/task/lambda_function.py", line 264, in on_intent
    return search(event)
  File "/var/task/lambda_function.py", line 1091, in search
    next_url, title = get_url_and_title(id)
  File "/var/task/lambda_function.py", line 840, in get_url_and_title
    return get_url_and_title_pytube(id)
  File "/var/task/lambda_function.py", line 921, in get_url_and_title_pytube
    first_stream = yt.streams.filter(only_audio=True, subtype='mp4').first()
  File "/var/task/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "/var/task/pytube/__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "/var/task/pytube/extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "/var/task/pytube/cipher.py", line 34, in __init__
    caller="__init__", pattern=var_regex.pattern
```

**Comment by wes1993** [comment]
Fixed for now

**Comment by DavidBerdik** [comment]
Thank you!
