### ISSUE TITLE
Alexa stop when a playlist has videos that violated Youtube policy

### ISSUE THREAD

**Issue by hoanglhifi** [wes1993/YouTubeForAlexa#23]
Context: 

I ask Alexa to play a playlist like "Taylor swift" | https://www.youtube.com/playlist?list=PLMEZyDHJojxNYSVgRCPt589DI5H7WT1ZK

then Alexa stop and nothing happens.
   
I saw in the log from Cloudwatch.  
It seem youtube-dl and pytube is failed with one URL because that video violated Youtube policy

```
[INFO] 2022-12-02T15:01:20.350Z bxxxxxx1-a824-4591-9a94-9xxxxxxxxxxc Getting youtube-dl url for https://www.youtube.com/watch?v=stO5l1aw6Ik

ERROR: This video has been removed for violating YouTube's policy on spam, deceptive practices, and scams

[INFO] 2022-12-02T15:01:20.486Z bxxxxxx1-a824-4591-9a94-9xxxxxxxxxxc youtube_dl error

[INFO] 2022-12-02T15:01:20.486Z bxxxxxx1-a824-4591-9a94-9xxxxxxxxxxc trying pytube

[INFO] 2022-12-02T15:01:20.607Z bxxxxxx1-a824-4591-9a94-9xxxxxxxxxxc Getting pytube url for https://www.youtube.com/watch?v=stO5l1aw6Ik

[ERROR] KeyError: 'streamingData' Traceback (most recent call last):   File "/var/task/lambda_function.py", line 252, in lambda_handler     return handle_playback(event)   File "/var/task/lambda_function.py", line 361, in handle_playback     return failed(event)   File "/var/task/lambda_function.py", line 1579, in failed     next_url, next_token, title = get_next_url_and_token(current_token, skip)   File "/var/task/lambda_function.py", line 1515, in get_next_url_and_token     next_url, title = get_url_and_title(next_id)   File "/var/task/lambda_function.py", line 887, in get_url_and_title     return get_url_and_title_youtube_dl(id)   File "/var/task/lambda_function.py", line 920, in get_url_and_title_youtube_dl     return get_url_and_title_pytube(id, False)   File "/var/task/lambda_function.py", line 969, in get_url_and_title_pytube     first_stream = yt.streams.filter(only_audio=True, subtype='mp4').first()   File "/var/task/pytube/__main__.py", line 296, in streams     return StreamQuery(self.fmt_streams)   File "/var/task/pytube/__main__.py", line 176, in fmt_streams     stream_manifest = extract.apply_descrambler(self.streaming_data)   File "/var/task/pytube/__main__.py", line 161, in streaming_data     return self.vid_info['streamingData']

END RequestId: bxxxxxx1-a824-4591-9a94-9xxxxxxxxxxc

REPORT RequestId: bxxxxxx1-a824-4591-9a94-9xxxxxxxxxxc Duration: 758.95 ms Billed Duration: 759 ms Memory Size: 512 MB Max Memory Used: 98 MB

START RequestId: bxxxxxx1-fd77-4385-a5ee-bsssssssssss Version: $LATEST

END RequestId: bxxxxxx1-fd77-4385-a5ee-bsssssssssss

REPORT RequestId: bxxxxxx1-fd77-4385-a5ee-bsssssssssss Duration: 1.70 ms Billed Duration: 2 ms Memory Size: 512 MB Max Memory Used: 98 MB
```

I hope someone faced this issue can help me with this. Many thanks.

**Comment by trinib** [comment]
same here
